apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /admin-controller-porch-role
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/version: tbd
  name: admin-controller-porch-role
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|admin-controller-porch-role'
rules:
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources
  - packagerevisions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - porch.kpt.dev
  resources:
  - packagerevisionresources/status
  - packagerevisions/status
  - packagerevisions/approval
  verbs:
  - get
  - update
  - patch
