apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: ndd-system/admin-controller-controller-role-binding
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/version: tbd
  name: admin-controller-controller-role-binding
  namespace: ndd-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|ndd-system|admin-controller-controller-role-binding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-controller-controller-role
subjects:
- kind: ServiceAccount
  name: admin-controller
  namespace: ndd-system
