apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: ndd-system/admin-controller-controller-role
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: admin
    app.kubernetes.io/part-of: admin
    app.kubernetes.io/version: tbd
  name: admin-controller-controller-role
  namespace: ndd-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|ndd-system|admin-controller-controller-role'
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - admin.yndd.io
  resources:
  - tenants
  - tenants/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
