apiVersion: v1
kind: Service
metadata: # kpt-merge: ndd-system/topology-controller-metrics-svc
  labels:
    app.kubernetes.io/component: tbd
    app.kubernetes.io/instance: tbd
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: topology
    app.kubernetes.io/part-of: topology
    app.kubernetes.io/version: tbd
    fn.kptgen.dev/metrics: topology-controller
  name: topology-controller-metrics-svc
  namespace: tenant2
spec:
  ports:
  - name: grpc
    port: 8443
    protocol: TCP
    targetPort: 443
  selector:
    fn.kptgen.dev/metrics: topology-controller
